eureka:
  instance:
    hostname: ${EUREKA_URL:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761}
server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: pontoquente
          uri: lb://PONTOQUENTE
          predicates:
            - Path=/pontoquente/**

management:
  endpoints:
    web:
      exposure:
        include: "*"


